# Generated by Django 4.1.5 on 2023-01-26 20:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EGridPlant',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False, verbose_name='Plant ID EGrid 2020')),
                ('pname', models.CharField(max_length=128, verbose_name='Plant Name')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
