# Generated by Django 4.1.5 on 2023-01-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='egridplant',
            name='capfac',
            field=models.DecimalField(decimal_places=4, null=True, max_digits=5, verbose_name='Plant capacity factor (annual production / nameplate)'),
        ),
        migrations.AddField(
            model_name='egridplant',
            name='coalflag',
            field=models.BooleanField(default=False, verbose_name='Flag indicating if the plant burned or generated any amount of coal'),
        ),
        migrations.AddField(
            model_name='egridplant',
            name='namepcap',
            field=models.FloatField(null=True, verbose_name='Plant nameplate (theoretical) capacity (MW)'),
        ),
        migrations.AddField(
            model_name='egridplant',
            name='numgen',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Number of generators'),
        ),
        migrations.AddField(
            model_name='egridplant',
            name='numunt',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Number of units'),
        ),
        migrations.AddField(
            model_name='egridplant',
            name='plch4an',
            field=models.IntegerField(null=True, verbose_name='Plant annual N2O emissions (lbs)'),
        ),
        migrations.AddField(
            model_name='egridplant',
            name='plco2an',
            field=models.IntegerField(null=True, verbose_name='Plant annual CH4 emissions (lbs)'),
        ),
        migrations.AddField(
            model_name='egridplant',
            name='plco2eqa',
            field=models.IntegerField(null=True, verbose_name='Plant annual Hg emissions (lbs)'),
        ),
        migrations.AddField(
            model_name='egridplant',
            name='plfuelct',
            field=models.CharField(blank=True, choices=[('COAL', 'Coal'), ('OIL', 'Oil'), ('GAS', 'Gas'), ('OFSL', 'Other fossil fuel'), ('NUCLEAR', 'Nuclear'), ('HYDRO', 'Hydro'), ('SOLAR', 'Solar'), ('WIND', 'Wind'), ('GEOTHERMAL', 'Geothermal'), ('OTHF', 'Waste heat, hydrogen, purchased or unknown'), ('BIOMASS', 'Biomass')], max_length=10, verbose_name='Plant primary fuel category'),
        ),
        migrations.AddField(
            model_name='egridplant',
            name='plhgan',
            field=models.IntegerField(null=True, verbose_name='Plant annual NOx total output emission rate (lb/MWh)'),
        ),
        migrations.AddField(
            model_name='egridplant',
            name='pln2oan',
            field=models.IntegerField(null=True, verbose_name='Plant annual CO2 equivalent emissions (tons)'),
        ),
        migrations.AddField(
            model_name='egridplant',
            name='plngenan',
            field=models.IntegerField(null=True, verbose_name='Plant annual net generation (MWh)'),
        ),
        migrations.AddField(
            model_name='egridplant',
            name='plngenoz',
            field=models.IntegerField(null=True, verbose_name='Plant annual NOx emissions (tons)'),
        ),
        migrations.AddField(
            model_name='egridplant',
            name='plnoxan',
            field=models.IntegerField(null=True, verbose_name='Plant ozone season NOx emissions (tons)'),
        ),
        migrations.AddField(
            model_name='egridplant',
            name='plnoxoz',
            field=models.IntegerField(null=True, verbose_name='Plant annual SO2 emissions (tons)'),
        ),
        migrations.AddField(
            model_name='egridplant',
            name='plprmfl',
            field=models.CharField(blank=True, choices=[('AB', 'Agricultural byproduct'), ('BFG', 'Blast furnace gas'), ('BIT', 'Bituminous coal'), ('BLQ', 'Black liquor'), ('COG', 'Coke oven gas'), ('DFO', 'Distillate fuel oil, light fuel oil, diesel oil'), ('GEO', 'Geothermal'), ('H', 'Hydrogen'), ('JF', 'Jet fuel'), ('KER', 'Kerosene'), ('LFG', 'Landfill gas'), ('LIG', 'Lignite coal'), ('MSW', 'Municipal solid waste '), ('MWH', 'Electricity used for energy storage (megawatt hour)'), ('NG', 'Natural gas'), ('NUC', 'Nuclear'), ('OBG', 'Other biomass gas (digester gas, methane, and other biomass gases)'), ('OBL', 'Other biomass liquids'), ('OBS', 'Other biomass solid'), ('OG', 'Other gas'), ('OTH', 'Other'), ('PC', 'Petroleum coke'), ('PG', 'Gaseous propane'), ('PRG', 'Process gas'), ('PUR', 'Purchased steam'), ('RC', 'Refined coal'), ('RFO', 'Residual fuel oil, heavy fuel oil, petroleum'), ('SGC', 'Coal-derived synthetic gas'), ('SLW', 'Sludge waste'), ('SUB', 'Subbituminous coal'), ('SUN', 'Solar'), ('TDF', 'Tire-derived fuel'), ('WAT', 'Water'), ('WC', 'Waste coal'), ('WDL', 'Wood, wood waste liquid'), ('WDS', 'Wood, wood waste solid'), ('WH', 'Waste heat'), ('WND', 'Wind'), ('WO', 'Waste oil')], max_length=3, verbose_name='Plant primary fuel'),
        ),
        migrations.AddField(
            model_name='egridplant',
            name='plso2an',
            field=models.IntegerField(null=True, verbose_name='Plant annual CO2 emissions (tons)'),
        ),
        migrations.AddField(
            model_name='egridplant',
            name='oprname',
            field=models.CharField(blank=True, max_length=50, verbose_name='Plant transmission or distribution system owner'),
        ),
        migrations.AddField(
            model_name='egridplant',
            name='pstatabb',
            field=models.CharField(blank=True, max_length=2, verbose_name='Plant state abbreviation'),
        ),
        migrations.AddField(
            model_name='egridplant',
            name='utlsrvnm',
            field=models.CharField(blank=True, max_length=128, verbose_name='Utility name'),
        ),
    ]
