# Generated by Django 4.1.5 on 2023-01-30 21:28

from django.db import migrations
from scripts import load


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_egridplant_capfac_egridplant_coalflag_and_more'),
    ]

    operations = [
        migrations.RunPython(load.run)
    ]
