# Generated by Django 4.1.5 on 2023-02-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_load_2020_data'),
    ]

    def set_latlon(apps, schema_editor):
        EGridPlant = apps.get_model('server', 'EGridPlant')
        for plant in EGridPlant.objects.all():
            plant.lat = plant.location[1] # Point is lon, lat
            plant.lon = plant.location[0]
            plant.save()

    def reverse_latlon(apps, schema_editor):
        pass


    operations = [
        migrations.AddField(
            model_name='egridplant',
            name='lat',
            field=models.FloatField(null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='egridplant',
            name='lon',
            field=models.FloatField(null=True, verbose_name='Longitude'),
        ),
        migrations.RunPython(set_latlon, reverse_latlon),
    ]
