# Generated by Django 4.1.5 on 2023-02-03 20:03

from django.db import migrations, models
from scripts import load

class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_egridplant_lat_egridplant_lon'),
    ]

    def reverse_pass(apps, schema_editor):
        pass

    operations = [
        migrations.RemoveField(
            model_name='egridplant',
            name='plngenoz',
        ),
        migrations.AlterField(
            model_name='egridplant',
            name='plch4an',
            field=models.IntegerField(null=True, verbose_name='Plant annual CH4 emissions (lbs)'),
        ),
        migrations.AlterField(
            model_name='egridplant',
            name='plco2an',
            field=models.IntegerField(null=True, verbose_name='Plant annual CO2 emissions (tons)'),
        ),
        migrations.AlterField(
            model_name='egridplant',
            name='plco2eqa',
            field=models.IntegerField(null=True, verbose_name='Plant annual CO2 equivalent emissions (tons)'),
        ),
        migrations.AlterField(
            model_name='egridplant',
            name='plhgan',
            field=models.IntegerField(null=True, verbose_name='Plant annual Hg emissions (lbs)'),
        ),
        migrations.AlterField(
            model_name='egridplant',
            name='pln2oan',
            field=models.IntegerField(null=True, verbose_name='Plant annual N2O emissions (lbs)'),
        ),
        migrations.AlterField(
            model_name='egridplant',
            name='plnoxan',
            field=models.IntegerField(null=True, verbose_name='Plant annual NOx emissions (tons)'),
        ),
        migrations.AlterField(
            model_name='egridplant',
            name='plnoxoz',
            field=models.IntegerField(null=True, verbose_name='Plant ozone season NOx emissions (tons)'),
        ),
        migrations.AlterField(
            model_name='egridplant',
            name='plso2an',
            field=models.IntegerField(null=True, verbose_name='Plant annual SO2 emissions (tons)'),
        ),
        migrations.RunPython(load.run, reverse_pass),
    ]
